{
 "title": "Sensor Node01",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sensor Node01",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")                                                                                                                                                   \n    |> range(start: -10m)                                                                                                                                                   \n    |> filter(fn: (r) => r._measurement == \"vibration\")                                                                                                                     \n    |> filter(fn: (r) => r._field == \"vibration_rms\")                                                                                                                       \n    |> filter(fn: (r) => r.node_id == \"node01\")"
    }
   ]
  },
  {
   "title": "Accelerometer (ax / ay / az)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")                                                                                                                                                   \n    |> range(start: -10m)\n    |> filter(fn: (r) => r._measurement == \"vibration\")\n    |> filter(fn: (r) => r._field == \"ax\" or r._field == \"ay\" or r._field == \"az\")                                                                                          \n    |> filter(fn: (r) => r.node_id == \"node01\")"
    }
   ]
  },
  {
   "title": "Gyroscope (gx / gy / gz)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")                                                                                                                                                   \n    |> range(start: -10m)                                                                                                                                                   \n    |> filter(fn: (r) => r._measurement == \"vibration\")                                                                                                                     \n    |> filter(fn: (r) => r._field == \"gx\" or r._field == \"gy\" or r._field == \"gz\")\n    |> filter(fn: (r) => r.node_id == \"node01\")"
    }
   ]
  },
  {
   "title": "Status Flags",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")                                                                                                                                                   \n    |> range(start: -10m)                                                                                                                                                   \n    |> filter(fn: (r) => r._measurement == \"vibration\")                                                                                                                     \n    |> filter(fn: (r) => r._field == \"flags\")\n    |> filter(fn: (r) => r.node_id == \"node01\") "
    }
   ]
  },
  {
   "title": "Sensor Faults",
   "type": "table",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")                                                                                                                                                   \n    |> range(start: -1h)                                                                                                                                                    \n    |> filter(fn: (r) => r._measurement == \"sensor_faults\")                                                                                                                 \n    |> filter(fn: (r) => r.node_id == \"node01\")"
    }
   ]
  }
 ]
}